[package]
name = "RustPacker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.22"
random-string = "1.0.0"
cargo = "0.65.0"
path-absolutize = "3.0.13"